### ISSUE TITLE
Implementation of software reset

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/PCA9634#10] opened 2022-05-16 19:25 UTC
This issue is split off from #8 - the main question is repeated here

### Implementation of software reset
In some instances it might be usefull to send a software reset to some/all chips. Currently, I do that manually, if required. I assume, some users might find this usefull, when debugging their software. In some applications I do a software reset before configuring the chip, since I then know that no old configuration is safed that might interfere. This is usefull when playing around with new code :-)

The datasheet states:

### Software Reset
The Software Reset Call (SWRST Call) allows all the devices in the I2C-bus to be reset to the power-up state value through a specific formatted I2C-bus command. To be performed correctly, it implies that the I2C-bus is functional and that there is no device hanging the bus.
The SWRST Call function is defined as the following:
1. A START command is sent by the I2C-bus master.
2. The reserved SWRST I2C-bus address ‘0000 011’ with the R/W bit set to ‘0’ (write) is sent by the I2C-bus master.
3. The PCA9634 device(s) acknowledge(s) after seeing the SWRST Call address ‘0000 0110’ (06h) only. If the R/W bit is set to ‘1’ (read), no acknowledge is returned to the I2C-bus master.
4. Once the SWRST Call address has been sent and acknowledged, the master sends 2 bytes with 2 specific values (SWRST data byte 1 and byte 2):
- Byte 1 = A5h: the PCA9634 acknowledges this value only. If byte 1 is not equal to A5h, the PCA9634 does not acknowledge it.
- Byte 2 = 5Ah: the PCA9634 acknowledges this value only. If byte 2 is not equal to 5Ah, then the PCA9634 does not acknowledge it. If more than 2 bytes of data are sent, the PCA9634 does not acknowledge any more.
5. Once the right 2 bytes (SWRST data byte 1 and byte 2 only) have been sent and correctly acknowledged, the master sends a STOP command to end the SWRST Call: the PCA9634 then resets to the default value (power-up value) and is ready to be addressed again within the specified bus free time (tBUF). The I2C-bus master must interpret a non-acknowledge from the PCA9634 (at any time) as a ‘SWRST Call Abort’. The PCA9634 does not initiate a reset of its registers. This happens only when the format of the SWRST Call sequence is not correct.

**Comment by Luxovious** [comment] 2022-05-16 20:13
BTW: I just checked, the software reset might also be interesting for your PCA9635 lib. It's **exactly** the same sequence.

**Comment by RobTillaart** [comment] 2022-05-16 20:19
Note - 7.1.4 Software Reset I2C-bus address

**Comment by RobTillaart** [comment] 2022-05-16 20:32
> BTW: I just checked, the software reset might also be interesting for your PCA9635 lib. It's **exactly** the same sequence.

Yup, the main diff between these libs is the channel count.

**Comment by RobTillaart** [comment] 2022-05-18 10:10
Came across this one - https://www.forward.com.au/pfod/ArduinoProgramming/I2C_ClearBus/index.html

Not a SW reset as you mean but interesting enough to keep the link.

update
- https://spellfoundry.com/2020/06/25/reliable-embedded-systems-recovering-arduino-i2c-bus-lock-ups/

**Comment by RobTillaart** [comment] 2022-05-18 10:35
### Software Reset function

Given the data sheet par. 7.6 description the code should look something like this.
Note: not tested - only found a few minutes to put first thoughts in code - might be too simple ;)

```cpp
//    FILE: I2C_software_reset.ino
//  AUTHOR: Rob Tillaart
// VERSION: 0.1.0
//    DATE: 2022-05-18
// PURPOSE: to be tested
//     URL: https://github.com/RobTillaart/PCA9634/issues/10

// WARNING: NOT TESTED YET

#include "Arduino.h"
#include "Wire.h"


int I2C_software_reset(TwoWire *wire)
{
  const uint8_t I2C_SW_RESET = 0x03;

  TwoWire* _wire = wire;

  // STEP 1..3
  _wire->beginTransmission(I2C_SW_RESET);
  // _wire->write(0x00);    // some platforms need this to send the address in write mode.
  int ack = _wire->endTransmission();
  Serial.println(ack);

  if (ack == 0)
  {
    // STEP 4..5
    _wire->beginTransmission(I2C_SW_RESET);
    _wire->write(0xA5);
    _wire->write(0x5A);
    ack = _wire->endTransmission();
  }
  return ack;
}

void setup()
{
  Serial.begin(115200);
  while (!Serial);
  Serial.println(__FILE__);

  int x = I2C_software_reset(&Wire);
  Serial.println(x);   //  should print 0 as both calls should be acknowledged.
}

void loop()
{
}

// -- END OF FILE --

```

function might need to add a forced delay for the tBUF time.

**Comment by Luxovious** [comment] 2022-05-30 12:50
I receive 4 instead of 0. I'm trying to poke around the code, however I didn't find the issue yet. Besides: the chip has not been resetted.

**Comment by RobTillaart** [comment] 2022-05-30 19:35
Need to find some time to dive into this, first prio is to get the PCA9634 right (we're close)

(merged the changes so far of the 34 into PCA9635@0.4.0 - I need to merge these two libs soon. The difference is the number of channels and some register addresses, but functional they are identical.

**Comment by RobTillaart** [comment] 2022-05-30 20:30
(just note to myself)
mmm - read the twi.c file of UNO (lowest level I2C) , and the value 4 gives no more info at first sight.

```cpp
uint8_t twi_writeTo(uint8_t address, uint8_t* data, uint8_t length, uint8_t wait, uint8_t sendStop)
{
...
  if (twi_error == 0xFF)
    return 0;	// success
  else if (twi_error == TW_MT_SLA_NACK)
    return 2;	// error: address send, nack received
  else if (twi_error == TW_MT_DATA_NACK)
    return 3;	// error: data send, nack received
  else
    return 4;	// other twi error
}
```

Need to understand  what the value of **twi_error** is and where it has been set. 
 (bedtime).

**Comment by RobTillaart** [comment] 2022-05-30 20:38
(note to myself)
read this - https://www.analog.com/media/en/technical-documentation/application-notes/54305147357414an686_0.pdf

**Comment by RobTillaart** [comment] 2022-06-09 15:22
@Luxovious 
Today I ported the SUB CALL and ALL CALL functions to my PCA9685 library - (nice 16 channel 12 bit PWM ).
And to check if all things are the same (no they were not) I had my quest through the datasheet of both the PCA9634 and the PCA9685. Solved all diffs I think. 

Having those two datasheets open I took a look at the section **7.6 SWRST**

#### PCA9634
2. The reserved SWRST I2C-bus address **‘0000 011’** with the R/W bit set to ‘0’ (write) is
sent by the I2C-bus master.
[PCA9685.pdf](https://github.com/RobTillaart/PCA9634/files/8871593/PCA9685.pdf)


#### PCA9685
2. The reserved SWRST I2C-bus address **‘0000 000’** with the R/W bit set to ‘0’ (write) is
sent by the I2C-bus master.

Where the PCA9634 uses **0x03** the PCA9685 mentions **0x00**.

So I looked at - https://www.nxp.com/docs/en/user-guide/UM10204.pdf  
page 16

![image](https://user-images.githubusercontent.com/462844/172881020-af577a07-b3b2-48a6-a236-b3748228539c.png)

More in depth
![image](https://user-images.githubusercontent.com/462844/172882027-a97aa61a-b709-4ed0-a7de-c8f0f6aebc6f.png)

and

![image](https://user-images.githubusercontent.com/462844/172881669-bce1ce04-e11c-4f04-8a26-a1eb944eda86.png)

---- 

based upon the specification of I2C the SWRST should look like
```cpp
void I2C_swrst()
{
  const uint8_t GENERIC_CALL = 0x00;
  const uint8_t SW_RESET = 0x06;
  
  Wire.beginTransmission(GENERIC_CALL);
  Wire.write(SW_RESET);
  int x = Wire.endTransmission(true);
  Serial.println(x);  // debug
}
```

Can you give it a try?

**Comment by RobTillaart** [comment] 2022-06-09 15:43
Or should I interpret it as 

```cpp
void I2C_swrst()
{
  const uint8_t GENERIC_CALL = 0x00;
  const uint8_t SW_RESET = 0x03;
  
  Wire.beginTransmission(GENERIC_CALL );  //  a.k.a. START byte
  int x = Wire.endTransmission(false);    //  do not send a stop (?)
  Wire.beginTransmission(SWRST_ADDR);     //  reset  (becomes 0x06)
  Wire.write(0xA5);                       //  magic byte 1
  Wire.write(0x5A);                       //  magic byte 2
  int y = Wire.endTransmission(true);     //  do send a stop

  Serial.print('\t');
  Serial.print(x);
  Serial.print('\t');
  Serial.print(y);
  Serial.print('\n');
}
```

**Comment by Luxovious** [comment] 2022-06-11 19:24
I'll try to check it next weekend. I won't be able to make it this weekend.

**Comment by Luxovious** [comment] 2022-06-21 19:31
Didn't check it yet, didn't forget about it.

**Comment by Luxovious** [comment] 2022-08-05 11:07
Hi Rob,
now, back from holiday and very relaxed I was able to take a moment to study the data sheet. Furthermore, I dug deep and I found an old software reset that I programmed in .c years ago. I am confident that it worked for the PCA9634. I used a i2c library for GCC which I found online back then.

```c
#define I2C_Reset		0b00000110
#define I2C_Reset_Byte1		0b10100101
#define I2C_Reset_Byte2		0b01011010

void i2cPCA9634_Reset (void){
	i2c_start(I2C_Reset);
	i2c_write(I2C_Reset_Byte1);
	i2c_write(I2C_Reset_Byte2);
	i2c_stop();
}
```

After double reading the data sheet I think the ALLCALLADR should not be sent, as it is not mentioned. The SWRST 0x03 addresses all PCA9634. Therefore, the code below (your code, adapted) should work out. I will check it and comment about it late today.

```cpp
void I2C_swrst()
{
  const uint8_t SW_RESET = 0x03;
  Wire.beginTransmission(SWRST_ADDR);     //  reset  (becomes 0x06)
  Wire.write(0xA5);                       //  magic byte 1
  Wire.write(0x5A);                       //  magic byte 2
  int y = Wire.endTransmission(true);     //  do send a stop

  Serial.print('\t');
  Serial.print(y);
  Serial.print('\n');
}
```

**Comment by Luxovious** [comment] 2022-08-05 15:27
All right, checked it. The code works just as intended. Interesting: y will become **0**. I did expect a **1**, however I did not dig deep into the wire library, so I cannot judge, if that is correct or wrong.
```cpp
void I2C_swrst()
{
  const uint8_t SW_RESET = 0x03;
  Wire.beginTransmission(SW_RESET);     //  reset  (becomes 0x06)
  Wire.write(0xA5);                       //  magic byte 1
  Wire.write(0x5A);                       //  magic byte 2
  int y = Wire.endTransmission(true);     //  do send a stop

  Serial.print('\t');
  Serial.print(y);
  Serial.print('\n');
}
```
As the software reset function is essentially calling all PCA9634, it should not be called within an instance of the class. Therefore, it could probably be adapted for the PCA9635 without duplication. Maybe with an `#if` function in the library which will be resolved by the compiler (to keep the code on the chip shorter/faster).
All in all, this function can be added to the master branch. 😊

I would love to help you to fuse both libraries (PCA9634 and PCA9635) together and test them. Unfortunately, I dont have a PCA9635 or a fitting breakout board which I could use to test the code.

**Comment by RobTillaart** [comment] 2022-08-05 15:42
> As the software reset function is essentially calling all PCA9634, it should not be called within an instance of the class.

Why not ?
Just document the effects properly should be enough warning for the users. 
(using the function / library is not mandatory)

----

Note: The user must/should  reconfigure the PCA9634 object after the **SW_RESET** with 
```cpp
void configure(uint8_t mode1_mask, uint8_t mode2_mask)
```
as these settings get lost ... (IIRC)

**Comment by Luxovious** [comment] 2022-08-05 18:40
> Why not ? Just document the effects properly should be enough warning for the users. (using the function / library is not mandatory)

Well, I assumed it could make a user think that it does affect the specific PCA9634 only. `ledArray1.swrst();` would indicate this. Imho, a function such as `void allPCA9634_swrst();` could be easier to read for those who don't read manuals/data sheets in depth. But that's just a though :-)


> Note: The user must/should reconfigure the PCA9634 object after the **SW_RESET** with
> 
> ```c++
> void configure(uint8_t mode1_mask, uint8_t mode2_mask)
> ```

That is correct. Furthermore, this should definately be documented, as this would be requirde for ALL PCA9634 chips in the I²C circuit.

**Comment by Luxovious** [comment] 2022-08-05 19:09
BTW: I can document it, if you want. Just let me know, when /if the code is implement it and I write something that you can copy/paste into the readme-file.

**Comment by RobTillaart** [comment] 2022-08-06 19:09
You have a good argument, it might be better as a (static) function that is part of the class .
Code should be guarded with some #ifdef construct so I can add the reset to PCA9635 and 9685 library too.
something like 
```cpp
#ifndef I2C_SWRESET
#define I2C_SWRESET 1
static void I2C_sw_reset()
{ 
  ...
}
#endif
```

Need to think it over if there are unmentioned arguments / consequences left.

Yes, some documentation would be needed, so if you have time

**Comment by RobTillaart** [comment] 2022-08-26 18:10
Note: The documentation should mention that SWRST will reset all devices that support it on the I2C bus.

**Comment by RobTillaart** [comment] 2022-08-30 11:46
@Luxovious 
FYI I started an I2C_scanner class in which I will add the SW reset too.  See - https://github.com/RobTillaart/I2C_SCANNER

As the NXP specifies different code I added a method selection. For the I2C scanner this seems valid.

```cpp
int I2C_SCANNER::softwareReset(uint8_t method)
{
  //  only support 0 and 1
  if (method > 1) return -999;
  if (method == 1)
  {
    //  from https://github.com/RobTillaart/PCA9634/issues/10#issuecomment-1206326417
   const uint8_t SW_RESET = 0x03;
   _wire->beginTransmission(SW_RESET);
   _wire->write(0xA5);
   _wire->write(0x5A);
   return _wire->endTransmission(true);
  }

  //  default - based upon NXP specification - UM10204.pdf - page 16
  _wire->beginTransmission(0x00);
  _wire->write(0x06);
  return _wire->endTransmission(true);
}
```

**Comment by RobTillaart** [comment] 2022-09-02 13:28
@Luxovious 
Created a develop branch that has the software reset as a function of the class.  (+ example)
The reason to make it a function of the class is that some boards have multiple I2C busses so one must be sure to reset the right one. 

If you have time, please give it a try.

**Closed as completed** 2022-09-05 11:14 UTC
Labels: enhancement

**Comment by Luxovious** [comment] 2022-09-11 12:31
Hi Rob, I have written a small documentation of the software reset. Feel free to use it for your readme-file.

### I2C Software reset
The goal of this function is to reset ALL PCA9634 devices on the bus. When using the software reset, ALL devices attached to the bus are set to their hardware startup conditions.
Generally, there are multiple definitions of software resets by the I²C inventor NXP. To accommodate this, two different modes for this function have been defined and tested (library version 0.2.2).

- **Method 1** is a tested method which is specific to the PCA9634. Since the number of different types of I²C chips is very large, side-effects on other chips might be possible. Before using this method, consult the data sheets of all chips on the bus to mitigate potential undefined states.
- **Method 0** is a somewhat “general” method which resets many chips on the I²C-bus. However, this method DOES NOT reset the PCA9634 chip. Therefore, consult the data sheet of all different chips on the bus to mitigate potential undefined states.

When only working with PCA9634 chips on a bus, only method 1 is required.

Code:
```cpp
ledArray.I2C_SoftwareReset(1); // for method 1
ledArray.I2C_SoftwareReset(0); // for method 0
```
In case you experience issues with this function on your chips (non-PCA9634), please give feedback, so the documentation can be improved.
For further details of the development, see - https://github.com/RobTillaart/PCA9634/issues/10#issuecomment-1206326417

**Comment by RobTillaart** [comment] 2022-09-11 13:43
Thanks, I will update the readme right away so it is in the next release.

**Comment by RobTillaart** [comment] 2022-09-11 13:56
I fixed this one for the PCA9634 right away - https://github.com/RobTillaart/PCA9635/issues/17
develop branch created, 0.2.3 build in progress :)

**Comment by RobTillaart** [comment] 2022-09-11 14:05
build succeeded, 0.2.3 released.
